services:
  - type: web
    name: skin-lesion-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
